export interface User {
  email: string;
  role: "influencer" | "brand";
  password?: string;
  name?: string;
  phone?: string;
  username?: string;
  bio?: string;
  niches?: string[];
  countries?: string[];
  instagramUsername?: string;
  instagramFollowers?: number | null;
  youtubeUsername?: string;
  youtubeFollowers?: number | null;
  twitterUsername?: string;
  twitterFollowers?: number | null;
  pastWorkLinks?: string[];
  avatar?: string;
  isVerified?: boolean;
  companyName?: string;
  industry?: string;
  companySize?: string;
  location?: string;
  website?: string;
  firstName?: string;
  lastName?: string;
  brandDescription?: string;
  minBudget?: number;
  maxBudget?: number;
  isProfileComplete: boolean;
}
